version: '3'
services:
  mysqldb:
    image: mysql
    container_name: mydatabase
    ports:
      - 3306:3306
    env_file:
      - ".env"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - "./data/db/mysql:/var/lib/mysql"
  phpMyAdmin:
    image: phpmyadmin/phpmyadmin
    container_name: MyPhpMyAdmin
    restart: always
    ports:
      - 8888:80
    env_file:
      - ".env"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - PMA_HOST=mysqldb
    depends_on:
      - mysqldb
    
    
